name: molberta
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - backoff==2.2.1
    - tokenizers
    - transformers==4.28.0
    - langchain
    - langchain_community
    - langchain-ollama