name: molberta
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - tqdm
  - scikit-learn
  - rdkit
  - jupyter
  - pip
  - pip:
    - deepchem
    - transformers==4.28.0
    - langchain
    - langchain_community
    - langchain-ollama
    - tokenizers
    - backoff==2.2.1
    - torch
    - scikit-multilearn
